Repository process-analytics/bonita-day-demo-2023, pull requests merged in 2023-03, with the labels that each got.

#1 docs: clean the README
  README.md
Labels: documentation

#3 feat: add navigation
  index.html
  src/breadcrumb.ts
  src/diagram.ts
  src/main.ts
Labels: enhancement

#4 feat: add case monitoring
  index.html
  package-lock.json
  package.json
  src/bpmn-elements.ts
  src/case-monitoring.ts
  src/main.ts
  src/radio-buttons.ts
  src/recommendation-data.ts
  src/style.css
Labels: enhancement

#5 feat: introduce the "process monitoring" use case
  src/process-monitoring.ts
  src/radio-buttons.ts
  src/style.css
Labels: enhancement

#6 feat: hide "case monitoring" data when switching to another use case
  src/case-monitoring.ts
  src/radio-buttons.ts
Labels: enhancement

#7 refactor: simplify some code and build scripts
  .github/actions/build/action.yml
  .github/workflows/build.yml
  .github/workflows/deploy-pr-preview.yml
  README.md
  package.json
  src/bpmn-elements.ts
  src/breadcrumb.ts
  src/diagram.ts
  src/main.ts
Labels: refactoring

#10 feat: add resource allocation interaction (1st step)
  src/bpmn-elements.ts
  src/case-monitoring-data.ts
  src/case-monitoring.ts
  src/diagram.ts
  src/style.css
  src/use-case-management.ts
  src/utils/bpmn-elements.ts
  src/utils/paths.ts
Labels: enhancement

#13 refactor: "happy path" deduces element types from the model
  src/bpmn-elements.ts
  src/process-monitoring.ts
Labels: refactoring

#14 fix: do not capitalize the text
  index.html
Labels: bug

#15 refactor(case-monitoring): split the code into classes
  src/case-monitoring.ts
  src/use-case-management.ts
Labels: refactoring

#16 refactor: better encapsulate MainProcessCaseMonitoring
  src/case-monitoring-data.ts
  src/case-monitoring.ts
  src/diagram.ts
  src/use-case-management.ts
Labels: refactoring

#17 refactor: do lazy initializations and improve view management
  src/breadcrumb.ts
  src/case-monitoring-data.ts
  src/case-monitoring.ts
  src/diagram.ts
  src/main.ts
  src/use-case-management.ts
Labels: refactoring

#20 refactor: rename the entry point script
  index.html
  src/index.ts
Labels: refactoring

#19 feat: display an advertise pane on demand
  index.html
  src/index.ts
  src/style.css
Labels: enhancement

#22 feat(supplier): add popover on retrieve email activity
  src/case-monitoring.ts
  src/case-monitoring/abstract.ts
  src/case-monitoring/supplier.ts
Labels: enhancement

#23 feat(supplier): add generated email popover
  src/case-monitoring.ts
  src/case-monitoring/supplier.ts
  src/style.css
Labels: enhancement

#24 fix(case-monitoring): remove listeners on popover elements
  src/case-monitoring-data.ts
  src/case-monitoring.ts
  src/case-monitoring/abstract.ts
  src/case-monitoring/supplier.ts
  src/diagram.ts
  src/use-case-management.ts
Labels: bug

#25 refactor: extract and move the "case-monitoring" code
  src/case-monitoring/main-process.ts
  src/case-monitoring/sub-process.ts
  src/use-case-management.ts
Labels: refactoring

#26 feat(case-monitoring): progressively highlight path of supplier
  package-lock.json
  package.json
  src/case-monitoring/supplier.ts
Labels: enhancement

#28 feat(supplier): hide supplier data
  src/case-monitoring/main-process.ts
  src/case-monitoring/supplier.ts
Labels: enhancement

#30 refactor: inject "tippy support" collaborator in `CaseMonitoring`
  src/case-monitoring/abstract.ts
  src/case-monitoring/main-process.ts
  src/case-monitoring/sub-process.ts
  src/case-monitoring/supplier.ts
  src/use-case-management.ts
Labels: refactoring

#31 refactor: move `case-monitoring` data files to a dedicated folder
  src/case-monitoring/abstract.ts
  src/case-monitoring/data-case.ts
  src/case-monitoring/data-recommendation.ts
  src/case-monitoring/main-process.ts
  src/case-monitoring/sub-process.ts
Labels: refactoring

#32 feat: introduce `ProcessExecutor` for the Supplier Contact process
  src/case-monitoring/main-process.ts
  src/case-monitoring/supplier-utils.ts
  src/case-monitoring/supplier.ts
Labels: enhancement

#40 fix(process-monitoring): fix glitch in edge animation
  src/diagrams/EC-purchase-orders-collapsed.bpmn
  src/process-monitoring.ts
Labels: bug

#44 refactor(supplier): simplify popover content management
  src/case-monitoring/supplier.ts
Labels: refactoring

#45 chore(deps-dev): bump typescript and vite
  package-lock.json
  package.json
Labels: dependencies, javascript

#46 fix(supplier): fix content outside popover
  src/style.css
Labels: bug

#62 fix(case-monitoring): no overlay on the running task of the sub-process
  src/case-monitoring/abstract.ts
  src/case-monitoring/main-process.ts
  src/case-monitoring/sub-process.ts
Labels: bug

#69 feat(happy-path): activate the "catch msg" flow at last
  src/process-monitoring.ts
Labels: enhancement

#70 feat(supplier): add actions on popover buttons
  src/case-monitoring/supplier.ts
Labels: enhancement

#72 feat(process-monitoring): replace overlay with popover
  src/process-monitoring.ts
Labels: enhancement

#65 refactor: improve css selectors for the main process popover
  src/case-monitoring/main-process.ts
Labels: refactoring

#71 feat(supplier): process executor manages popovers
  src/case-monitoring/supplier-utils.ts
  src/case-monitoring/supplier.ts
  src/utils/shared.ts
Labels: enhancement

#77 refactor(process-monitoring): put the whole code in a class
  src/process-monitoring.ts
  src/use-case-management.ts
Labels: refactoring

#79 feat(case-monitoring): improve the content of the popovers
  src/case-monitoring/data-recommendation.ts
  src/case-monitoring/main-process.ts
  src/case-monitoring/sub-process.ts
  src/style.css
Labels: enhancement

#84 feat(supplier): add gpt answers
  src/case-monitoring/supplier-utils.ts
  src/case-monitoring/supplier.ts
Labels: enhancement

#85 feat(process-monitoring): fix content and delay of overlay
  src/process-monitoring.ts
Labels: enhancement

#34 feat(supplier): pause/resume main process
  src/case-monitoring/abstract.ts
  src/case-monitoring/main-process.ts
  src/case-monitoring/supplier.ts
Labels: enhancement

#87 feat(case-monitoring): rework the 'Supplier Contact' popovers
  src/case-monitoring/abstract.ts
  src/case-monitoring/main-process.ts
  src/case-monitoring/supplier.ts
  src/index.ts
  src/process-monitoring.ts
  src/style.css
Labels: enhancement

#88 refactor(process-monitoring): add "popover show delay" constant
  src/process-monitoring.ts
Labels: refactoring

#89 refactor(case-monitoring): simplify popovers in "Supplier Contact"
  src/case-monitoring/supplier-utils.ts
  src/case-monitoring/supplier.ts
Labels: refactoring

#92 fix(case-monitoring): disable use-case switch in "Supplier"
  src/case-monitoring/supplier.ts
  src/use-case-selectors.ts
Labels: bug

#90 feat(supplier): add overlay on edge to count the number of visits
  src/case-monitoring/supplier-utils.ts
Labels: enhancement

#91 feat(subprocess): display notification when clicking on "assign" button
  package-lock.json
  package.json
  src/case-monitoring/sub-process.ts
Labels: enhancement

#94 feat(supplier): display notification at the end of the execution
  src/case-monitoring/sub-process.ts
  src/case-monitoring/supplier-utils.ts
  src/utils/shared.ts
Labels: enhancement

#95 refactor: reorganize notifications
  src/case-monitoring/sub-process.ts
  src/case-monitoring/supplier-utils.ts
  src/index.ts
  src/utils/shared.ts
Labels: refactoring

#96 docs: explain the content of the demo in the README
  README.md
Labels: documentation

#100 feat(case-monitoring): improve design activities
  src/case-monitoring/abstract.ts
  src/case-monitoring/main-process.ts
  src/case-monitoring/sub-process.ts
  src/style.css
Labels: enhancement
